stages:
  - start child pipelines

fastapi:
  stage: start child pipelines
  trigger:
    include: .gitlab-ci-fastapi.yml
    strategy: depend

flower:
  stage: start child pipelines
  trigger:
    include: .gitlab-ci-flower.yml
    strategy: depend
