version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: creative-ai-fastapi
    volumes:
      - ./fastapi:/fastapi
    ports:
      - '5000:5000'
    environment:
      - PUBLISH_TASK_QUEUE=creative-ai-task
      - CONSUME_RESULT_QUEUE=creative-ai-result
      - RABBIT_HOST=rabbitmq
      - PORT=5000
    depends_on:
      - rabbitmq

  ml-worker:
    build:
      context: ./ml_worker
      dockerfile: Dockerfile
    container_name: creative-ai-ml-worker
    volumes:
      - ./ml_worker:/ml_worker
    ports:
      - '5001:5001'
    environment:
      - CONSUME_TASK_QUEUE=creative-ai-task
      - PUBLISH_RESULT_QUEUE=creative-ai-result
      - RABBIT_HOST=rabbitmq
      - PORT=5001
    depends_on:
      - rabbitmq

volumes:
  data: