version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    env_file:
      - rabbitmq.env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile-fastapi
    container_name: creative-ai-fastapi
    volumes:
      - ./backend:/fastapi
    ports:
      - '5000:5000'
    env_file:
      - logzio.env
      - redis.env
      - rabbitmq.env
    environment:
      - TASK_QUEUE=generate_image
      - PORT=5000
    depends_on:
      - rabbitmq
      - redis

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile-celery-worker
    container_name: creative-ai-celery-worker
    volumes:
      - ./backend/app:/ml_worker
    ports:
      - '5001:5001'
    env_file:
      - logzio.env
      - redis.env
      - rabbitmq.env
    environment:
      - TASK_QUEUE=generate_image
      - PORT=5001
    depends_on:
      - rabbitmq
      - redis

  celery-flower:
    build:
      context: ./backend
      dockerfile: Dockerfile-celery-flower
    container_name: creative-ai-celery-flower
    volumes:
      - ./backend/app:/flower
    env_file:
      - redis.env
      - rabbitmq.env
    ports:
        - '5555:5555'
    depends_on:
      - rabbitmq
      - redis

volumes:
  data: