version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile-fastapi
    container_name: creative-ai-fastapi
    volumes:
      - ./backend:/fastapi
    ports:
      - '5000:5000'
    env_file:
      - logzio.env
    environment:
#      NOTE: This is only for local development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CELERY_DB_INDEX=10
      - REDIS_STORE_DB_INDEX=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
      - TASK_QUEUE=generate_image
      - PORT=5000
    depends_on:
      - rabbitmq
      - redis

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile-celery-worker
    container_name: creative-ai-celery-worker
    volumes:
      - ./backend/app:/ml_worker
    ports:
      - '5001:5001'
    env_file:
      - logzio.env
    environment:
#      NOTE: This is only for local development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CELERY_DB_INDEX=10
      - REDIS_STORE_DB_INDEX=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
      - TASK_QUEUE=generate_image
      - PORT=5001
    depends_on:
      - rabbitmq
      - redis

  celery-flower:
    build:
      context: ./backend
      dockerfile: Dockerfile-celery-flower
    container_name: creative-ai-celery-flower
    volumes:
      - ./backend/app:/flower
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CELERY_DB_INDEX=10
      - REDIS_STORE_DB_INDEX=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    ports:
        - '5555:5555'
    depends_on:
      - rabbitmq
      - redis

volumes:
  data: