version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: creative-ai-fastapi
    volumes:
      - ./fastapi:/code
    ports:
      - '5000:5000'

volumes:
  data: