FROM python:3.9-slim-buster

# Create a virtual environment
ENV VIRTUAL_ENV=/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./requirements-celery.txt ./

RUN pip install --upgrade pip

RUN pip install -r requirements-celery.txt

COPY ./app/celery_worker celery_worker

COPY ./app/__init__.py ./

COPY ./app/config.py ./

COPY ./app/logging_config.py ./

CMD cd / && python3 --version && celery -A celery_worker.tasks worker --loglevel=info -Q $TASK_QUEUE
