FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel

# Create a virtual environment
ENV VIRTUAL_ENV=/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# intall git in Docker
# SEE: https://github.com/NVIDIA/nvidia-docker/issues/1632#issuecomment-1112667716
RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list

RUN apt-get update
RUN apt-get install -y git

# Celery worker
COPY ./requirements-celery.txt ./

RUN pip install --upgrade pip

RUN pip install -r requirements-celery.txt

COPY ./app/celery_worker celery_worker

COPY ./app/__init__.py ./

COPY ./app/config.py ./

COPY ./app/logging_config.py ./

# remove the mock ml model
RUN rm -rf ./celery_worker/style_diffusion.py

# Clone stable diffusion model
RUN git clone https://github.com/bramantyois/sd_art.git

# copy the model to the worker folder
RUN cp -r sd_art/src/models/ ./celery_worker

# Run the worker
# CMD python -c import torch; print(torch.cuda.is_available())
CMD cd / && python3 --version && celery -A celery_worker.tasks worker -n $WORKER_NAME --loglevel=info -Q $TASK_QUEUE
