FROM python:3.9-slim-buster

COPY ./requirements-celery-flower.txt ./

# Create a virtual environment
ENV VIRTUAL_ENV=/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip

RUN pip install -r requirements-celery-flower.txt

COPY ./app/celery_worker ./celery_worker

COPY ./app/__init__.py ./

COPY ./app/config.py ./

COPY app/logging_config.py ./

# --purge_offline_workers: Time (in seconds) after which offline workers are automatically removed from dashboard.
CMD celery -A celery_worker.tasks flower --broker=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_CELERY_DB_INDEX} --port=${PORT} --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD} -Q ${TASK_QUEUE} --purge_offline_workers=600
