FROM python:3.9-slim-buster

COPY ./install-nginx.sh /

RUN bash /install-nginx.sh

# Remove default configuration from Nginx
RUN rm /etc/nginx/conf.d/default.conf

COPY ./requirements-celery.txt ./

RUN pip install --upgrade pip

RUN pip install -r requirements-celery.txt

COPY ./app/celery_worker ./celery_worker

COPY ./app/__init__.py ./

COPY ./app/config.py ./

COPY app/logging_config.py ./

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD celery -A celery_worker.tasks flower --broker=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_CELERY_DB_INDEX} --port=${PORT} --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
