FROM python:3.9-slim-buster

COPY ./requirements-celery.txt /usr/src/

RUN pip install --upgrade pip

RUN pip install -r /usr/src/requirements-celery.txt

RUN mkdir /usr/src/flower

COPY ./app/celery_worker /usr/src/flower/celery_worker

COPY ./app/__init__.py /usr/src/flower/

COPY ./app/config.py /usr/src/flower/

WORKDIR /usr/src/flower

# Sleep 10 seconds to wait for the RabbitMQ container to be ready
# SEE also: https://docs.docker.com/compose/startup-order/
CMD sleep 10 && celery -A celery_worker.tasks flower --broker=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
