FROM python:3.9-slim-buster

WORKDIR /fastapi

COPY . .

ENV VIRTUAL_ENV=/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip

RUN pip install --no-cache-dir --upgrade -r requirements-api.txt

WORKDIR /fastapi/app

ENV PORT 5000

CMD uvicorn main:app --host 0.0.0.0 --port $PORT --reload