FROM python:3.9-buster

WORKDIR /fastapi

COPY . .

ENV VIRTUAL_ENV=/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip

RUN pip install --no-cache-dir --upgrade -r requirements-api.txt

WORKDIR /fastapi/app

ENV PORT 5000

# Sleep 10 seconds to wait for the RabbitMQ container to be ready
# SEE also: https://docs.docker.com/compose/startup-order/
CMD sleep 10 && uvicorn main:app --host 0.0.0.0 --port $PORT --reload